# Generated by Django 6.1.1 on 2026-09-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Motocicleta'), ('caminhao', 'Caminhão')], max_length=20, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('combustivel', models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('flex', 'Flex'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='Combustível')),
                ('quilometragem', models.IntegerField(default=0, verbose_name='Quilometragem')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
            ],
        ),
    ]
